<?php

// =====================================================================

// !!  路由文件由 bizadmin 自动生成，请不要手动修改。

// !!  Route file auto generated by bizadmin, don't modify it manually.

// =====================================================================

use DagaSmart\BizAdmin\Admin;
use Illuminate\Routing\Router;
use Illuminate\Support\Facades\Route;

Route::group([
    'domain'     => Admin::config('admin.route.domain'),
    'prefix'     => Admin::config('admin.route.prefix'),
    'middleware' => Admin::config('admin.route.middleware'),
], function (Router $router) {
    // 自由世界
    $router->resource('admin_apis_testes', \Biz\Chat\Http\Controllers\AdminApisTesteController::class);

});